env: "dev" # "prod"

server:
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s

database:
  host: "postgres"
  port: 5432
  user: "admin"
  password: "super_admin_password123"
  database: "docs"
  ssl_mode: "disable"

redis:
  address: "redis:6379"
  password: ""
  db: 0

auth:
  admin_token: "super_secret_admin_token"
  token_duration: "24h"
  cache_duration: "1h"

storage:
  path: "/app/uploads"
  max_size: 10485760 # 10 MB в байтах
  allowed_mimes:
    - "application/json"
    - "application/pdf"
    - "image/png"
    - "image/jpeg"
